steps:
  # Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}',
      '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest',
      '.'
    ]
    id: 'build-image'

  # Push da imagem para Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}'
    ]
    id: 'push-image'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'
    ]
    id: 'push-latest'
    waitFor: ['build-image']

  # Deploy no Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', '${_SERVICE_NAME}',
      '--image', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}',
      '--platform', 'managed',
      '--region', '${_REGION}',
      '--allow-unauthenticated',
      '--memory', '512Mi',
      '--cpu', '1',
      '--max-instances', '10',
      '--set-env-vars', 'GCP_PROJECT_ID=${PROJECT_ID},VM_NAME=${_VM_NAME},VM_ZONE=${_VM_ZONE}'
    ]
    id: 'deploy-cloud-run'
    waitFor: ['push-image']

# Variáveis substituíveis (agora usando São Paulo - southamerica-east1)
substitutions:
  _REGION: 'southamerica-east1'
  _REPOSITORY: 'acai-containers'
  _SERVICE_NAME: 'acai-vm-controller'
  _VM_NAME: 'acai-detector-vm'
  _VM_ZONE: 'southamerica-east1-a'

# Configurações do build (usando padrão gratuito)
options:
  logging: CLOUD_LOGGING_ONLY

# Timeout do build
timeout: '1200s'
